version: '3.9'
services:
    iobroker:
        image: 'buanet/iobroker:${IOBROKER_VERSION}'
        restart: always
        hostname: ${IOBROKER_HOSTNAME}
        container_name: iobroker
        environment:
            - USBDEVICES=
            - TZ=Europe/Berlin
            - ZWAVE=false
            - AVAHI=false
            - IOB_STATESDB_TYPE=jsonl
            - IOB_STATESDB_PORT=9000
            - IOB_STATESDB_HOST=0.0.0.0
            - IOB_OBJECTSDB_TYPE=jsonl
            - IOB_OBJECTSDB_PORT=9001
            - IOB_OBJECTSDB_HOST=0.0.0.0
            - IOB_MULTIHOST=master
            - IOB_ADMINPORT=8081
            - SETGID=1000
            - SETUID=1000
        volumes:
            - '${IOBROKER_PATH}:/opt/iobroker:rw'
        networks:
            host: {}

networks:
    host: {}
